language: php

matrix:
  include:
    - php: 5.2
      env: NODE_VERSION=6
    - php: 5.6
      env: NODE_VERSION=6
    - php: 7.0
      env: NODE_VERSION=6
    - php: 7.1
      env: NODE_VERSION=7

before_script:
  - nvm install $NODE_VERSION && nvm use $NODE_VERSION

script:
  - npm install && npm test
