language: php

matrix:
  include:
    - php: 5.2
      env: NODE_VERSION=6
      dist: precise
    - php: 5.6
      env: NODE_VERSION=6
    - php: 7.3
      env: NODE_VERSION=7
    - php: 7.4
      env: NODE_VERSION=7
    - php: 8.0
      env: NODE_VERSION=16

before_script:
  - nvm install $NODE_VERSION && nvm use $NODE_VERSION

script:
  - npm install && npm test
