name: PHP Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [develop]

jobs:
  build:

    strategy:
      matrix:
        php-version: [7.3, 7.4, 8.0, 8.1]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "xdebug"
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2
          ini-values: error_reporting=-1

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "PHP Tests"
        run: npm run test-php
